### ISSUE TITLE
How to define a unary matcher?

### ISSUE THREAD

**Issue by jdickey** [wojtekmach/minitest-matchers#9]
I want to define a matcher so that, given a class

``` ruby
class Foo
  # ...
  def valid?
    [true, false].sample
  end
  # ...
}
```

I can write a spec like

``` ruby
describe 'Foo'
  describe '#valid'
    let(:obj) { Foo.new }

    it 'should be valid' do
      expect(obj).must_be_valid
    end
    # ...
```

rather than the current

``` ruby
describe 'Foo'
  describe '#valid'
    let(:obj) { Foo.new }

    it 'should be valid' do
      expect(obj.valid?).must_equal true
    end
    # ...
```

Does this capability already exist and I'm just flubbing it? Or are there plans for it?

**Comment by wojtekmach** [comment]
Hey, this functionality exists however with a slightly more verbose syntax, you can check out example in test suite. Essentially you want to define a matcher (responds to `#matches?`, `#failure_message` etc) and then register it with `Minitest::Test.register_matcher`. I don't yet have plans to extend it further

**Comment by jdickey** [comment]
I looked at the [test suite](https://github.com/wojtekmach/minitest-matchers/blob/master/test/minitest/matchers_test.rb), and read [`KindOfMatcher`](https://github.com/wojtekmach/minitest-matchers/blob/master/test/minitest/matchers_test.rb) several times. I just went back and took a hard look at it, and realised that how it's actually coded is sort of "backwards" from how I was reading it. The parameter to `#initialize` *initialises the value being tested against*, whereas the `subject` passed to `#matches?` is the *object under test*. Finally, the light goes on. *thud*

So I quickly coded up

```ruby
# Class to test whether an object responds to the `#valid?` message and, if so,
# whether sending `#valid?` produces the expected value (`true` or `false`).
#
# Usage:
#
#     expect(some_valid_object).must be_valid
#     expect(some_invalid_object).wont be_valid
#
# However, *note that* the `#failure_message_for_should` and
# `#failure_message_for_should_not` methods are not called. For example, the
# error message produced by
#
#     expect(some_valid_object).wont be_valid
#
# is
#     Minitest::Assertion: Expected: true
#       Actual: nil
#
# What am I missing?
#
class ValidityMatcher
  # No parameters. Your instance under test is passed into `#matches?`; it's not
  # dependent on anything that needs to be injected here.
  def initialize
    self
  end

  # Should be a standard MiniTest matcher method, used to produce failure
  # messages, but see the comment block above the start of this class.
  def description
    "be valid"
  end

  # "Main worker" of the matcher class, called by
  # `MiniTest::Assertions#assert_must` and `MiniTest::Assertions#assert_wont`.
  #
  # Parameter:
  #
  # * `subject` -- Object instance being tested.
  #
  # Returns:
  #
  # * `true` -- Object responds to `#valid?` and responds `true` when sent.
  # * `false` -- Object either does not respond to `#valid?` or responds `false`
  #              when sent.
  def matches?(subject)
    subject.respond_to?(:valid?) && subject.valid?
  end

  # Should be a standard MiniTest matcher method, used to produce failure
  # messages when an object instance unexpectedly returns `false` from
  # `#matches?` (see above).
  def failure_message_for_should
    "expected to " + description
  end

  # Should be a standard MiniTest matcher method, used to produce failure
  # messages when an object instance unexpectedly returns `true` from
  # `#matches?` (see above).
  def failure_message_for_should_not
    "expected not to " + description
  end
end # class ValidityMatcher

def be_valid
  ValidityMatcher.new
end
```

I can see the points in the source for [`MiniTest::Assertions#assert_must`](https://github.com/wojtekmach/minitest-matchers/blob/master/lib/minitest/matchers.rb#L14-L26) and [`MiniTest::Assertions#assert_wont`](https://github.com/wojtekmach/minitest-matchers/blob/master/lib/minitest/matchers.rb#L14-L26) where `#failure_message_for_should` and `#failure_message_for_should_not`, respectively, should be called, yet the error messages I expect aren't being produced. Any idea why?

**Comment by jdickey** [comment]
Well, that’s one way of (not) answering the question. The project that led to this issue being filed went EOL about a month ago so, yeah, no additional harm done; it would have been nice to noodle this out one of these days. Thanks for maintaining the package as it is anyway!
